// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tracking.proto

package com.amazon.proto;

public final class TrackingEventProtos {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_TrackingEvent_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_TrackingEvent_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\016tracking.proto\"\260\001\n\rTrackingEvent\022\021\n\tpr" +
                        "ogramid\030\001 \001(\t\022\020\n\010checksum\030\002 \001(\t\022\023\n\013custo" +
                        "mer_id\030\003 \001(\005\022\022\n\nuser_agent\030\004 \001(\t\022\024\n\014prog" +
                        "ram_name\030\005 \001(\t\022\025\n\rcustomer_name\030\006 \001(\t\022\020\n" +
                        "\010is_valid\030\007 \001(\010\022\022\n\nmessage_id\030\010 \001(\tB\'\n\020c" +
                        "om.amazon.protoB\023TrackingEventProtosb\006pr" +
                        "oto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_TrackingEvent_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_TrackingEvent_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_TrackingEvent_descriptor,
                new java.lang.String[]{"Programid", "Checksum", "CustomerId", "UserAgent", "ProgramName", "CustomerName", "IsValid", "MessageId",});
    }

    private TrackingEventProtos() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface TrackingEventOrBuilder extends
            // @@protoc_insertion_point(interface_extends:TrackingEvent)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string programid = 1;</code>
         */
        java.lang.String getProgramid();

        /**
         * <code>string programid = 1;</code>
         */
        com.google.protobuf.ByteString
        getProgramidBytes();

        /**
         * <code>string checksum = 2;</code>
         */
        java.lang.String getChecksum();

        /**
         * <code>string checksum = 2;</code>
         */
        com.google.protobuf.ByteString
        getChecksumBytes();

        /**
         * <code>int32 customer_id = 3;</code>
         */
        int getCustomerId();

        /**
         * <code>string user_agent = 4;</code>
         */
        java.lang.String getUserAgent();

        /**
         * <code>string user_agent = 4;</code>
         */
        com.google.protobuf.ByteString
        getUserAgentBytes();

        /**
         * <code>string program_name = 5;</code>
         */
        java.lang.String getProgramName();

        /**
         * <code>string program_name = 5;</code>
         */
        com.google.protobuf.ByteString
        getProgramNameBytes();

        /**
         * <code>string customer_name = 6;</code>
         */
        java.lang.String getCustomerName();

        /**
         * <code>string customer_name = 6;</code>
         */
        com.google.protobuf.ByteString
        getCustomerNameBytes();

        /**
         * <code>bool is_valid = 7;</code>
         */
        boolean getIsValid();

        /**
         * <code>string message_id = 8;</code>
         */
        java.lang.String getMessageId();

        /**
         * <code>string message_id = 8;</code>
         */
        com.google.protobuf.ByteString
        getMessageIdBytes();
    }

    /**
     * Protobuf type {@code TrackingEvent}
     */
    public static final class TrackingEvent extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:TrackingEvent)
            TrackingEventOrBuilder {
        public static final int PROGRAMID_FIELD_NUMBER = 1;
        public static final int CHECKSUM_FIELD_NUMBER = 2;
        public static final int CUSTOMER_ID_FIELD_NUMBER = 3;
        public static final int USER_AGENT_FIELD_NUMBER = 4;
        public static final int PROGRAM_NAME_FIELD_NUMBER = 5;
        public static final int CUSTOMER_NAME_FIELD_NUMBER = 6;
        public static final int IS_VALID_FIELD_NUMBER = 7;
        public static final int MESSAGE_ID_FIELD_NUMBER = 8;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:TrackingEvent)
        private static final com.amazon.proto.TrackingEventProtos.TrackingEvent DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<TrackingEvent>
                PARSER = new com.google.protobuf.AbstractParser<TrackingEvent>() {
            public TrackingEvent parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new TrackingEvent(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new com.amazon.proto.TrackingEventProtos.TrackingEvent();
        }

        private volatile java.lang.Object programid_;
        private volatile java.lang.Object checksum_;
        private int customerId_;
        private volatile java.lang.Object userAgent_;
        private volatile java.lang.Object programName_;
        private volatile java.lang.Object customerName_;
        private boolean isValid_;
        private volatile java.lang.Object messageId_;
        private byte memoizedIsInitialized = -1;

        // Use TrackingEvent.newBuilder() to construct.
        private TrackingEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private TrackingEvent() {
            programid_ = "";
            checksum_ = "";
            customerId_ = 0;
            userAgent_ = "";
            programName_ = "";
            customerName_ = "";
            isValid_ = false;
            messageId_ = "";
        }

        private TrackingEvent(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            java.lang.String s = input.readStringRequireUtf8();

                            programid_ = s;
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            checksum_ = s;
                            break;
                        }
                        case 24: {

                            customerId_ = input.readInt32();
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            userAgent_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            programName_ = s;
                            break;
                        }
                        case 50: {
                            java.lang.String s = input.readStringRequireUtf8();

                            customerName_ = s;
                            break;
                        }
                        case 56: {

                            isValid_ = input.readBool();
                            break;
                        }
                        case 66: {
                            java.lang.String s = input.readStringRequireUtf8();

                            messageId_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.amazon.proto.TrackingEventProtos.internal_static_TrackingEvent_descriptor;
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(com.amazon.proto.TrackingEventProtos.TrackingEvent prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static com.amazon.proto.TrackingEventProtos.TrackingEvent getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<TrackingEvent> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.amazon.proto.TrackingEventProtos.internal_static_TrackingEvent_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.amazon.proto.TrackingEventProtos.TrackingEvent.class, com.amazon.proto.TrackingEventProtos.TrackingEvent.Builder.class);
        }

        /**
         * <code>string programid = 1;</code>
         */
        public java.lang.String getProgramid() {
            java.lang.Object ref = programid_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                programid_ = s;
                return s;
            }
        }

        /**
         * <code>string programid = 1;</code>
         */
        public com.google.protobuf.ByteString
        getProgramidBytes() {
            java.lang.Object ref = programid_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                programid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string checksum = 2;</code>
         */
        public java.lang.String getChecksum() {
            java.lang.Object ref = checksum_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                checksum_ = s;
                return s;
            }
        }

        /**
         * <code>string checksum = 2;</code>
         */
        public com.google.protobuf.ByteString
        getChecksumBytes() {
            java.lang.Object ref = checksum_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                checksum_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>int32 customer_id = 3;</code>
         */
        public int getCustomerId() {
            return customerId_;
        }

        /**
         * <code>string user_agent = 4;</code>
         */
        public java.lang.String getUserAgent() {
            java.lang.Object ref = userAgent_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                userAgent_ = s;
                return s;
            }
        }

        /**
         * <code>string user_agent = 4;</code>
         */
        public com.google.protobuf.ByteString
        getUserAgentBytes() {
            java.lang.Object ref = userAgent_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                userAgent_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string program_name = 5;</code>
         */
        public java.lang.String getProgramName() {
            java.lang.Object ref = programName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                programName_ = s;
                return s;
            }
        }

        /**
         * <code>string program_name = 5;</code>
         */
        public com.google.protobuf.ByteString
        getProgramNameBytes() {
            java.lang.Object ref = programName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                programName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string customer_name = 6;</code>
         */
        public java.lang.String getCustomerName() {
            java.lang.Object ref = customerName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                customerName_ = s;
                return s;
            }
        }

        /**
         * <code>string customer_name = 6;</code>
         */
        public com.google.protobuf.ByteString
        getCustomerNameBytes() {
            java.lang.Object ref = customerName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                customerName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>bool is_valid = 7;</code>
         */
        public boolean getIsValid() {
            return isValid_;
        }

        /**
         * <code>string message_id = 8;</code>
         */
        public java.lang.String getMessageId() {
            java.lang.Object ref = messageId_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                messageId_ = s;
                return s;
            }
        }

        /**
         * <code>string message_id = 8;</code>
         */
        public com.google.protobuf.ByteString
        getMessageIdBytes() {
            java.lang.Object ref = messageId_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                messageId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getProgramidBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, programid_);
            }
            if (!getChecksumBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, checksum_);
            }
            if (customerId_ != 0) {
                output.writeInt32(3, customerId_);
            }
            if (!getUserAgentBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userAgent_);
            }
            if (!getProgramNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, programName_);
            }
            if (!getCustomerNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 6, customerName_);
            }
            if (isValid_ != false) {
                output.writeBool(7, isValid_);
            }
            if (!getMessageIdBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 8, messageId_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getProgramidBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, programid_);
            }
            if (!getChecksumBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, checksum_);
            }
            if (customerId_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(3, customerId_);
            }
            if (!getUserAgentBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userAgent_);
            }
            if (!getProgramNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, programName_);
            }
            if (!getCustomerNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, customerName_);
            }
            if (isValid_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(7, isValid_);
            }
            if (!getMessageIdBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, messageId_);
            }
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof com.amazon.proto.TrackingEventProtos.TrackingEvent)) {
                return super.equals(obj);
            }
            com.amazon.proto.TrackingEventProtos.TrackingEvent other = (com.amazon.proto.TrackingEventProtos.TrackingEvent) obj;

            boolean result = true;
            result = result && getProgramid()
                    .equals(other.getProgramid());
            result = result && getChecksum()
                    .equals(other.getChecksum());
            result = result && (getCustomerId()
                    == other.getCustomerId());
            result = result && getUserAgent()
                    .equals(other.getUserAgent());
            result = result && getProgramName()
                    .equals(other.getProgramName());
            result = result && getCustomerName()
                    .equals(other.getCustomerName());
            result = result && (getIsValid()
                    == other.getIsValid());
            result = result && getMessageId()
                    .equals(other.getMessageId());
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + PROGRAMID_FIELD_NUMBER;
            hash = (53 * hash) + getProgramid().hashCode();
            hash = (37 * hash) + CHECKSUM_FIELD_NUMBER;
            hash = (53 * hash) + getChecksum().hashCode();
            hash = (37 * hash) + CUSTOMER_ID_FIELD_NUMBER;
            hash = (53 * hash) + getCustomerId();
            hash = (37 * hash) + USER_AGENT_FIELD_NUMBER;
            hash = (53 * hash) + getUserAgent().hashCode();
            hash = (37 * hash) + PROGRAM_NAME_FIELD_NUMBER;
            hash = (53 * hash) + getProgramName().hashCode();
            hash = (37 * hash) + CUSTOMER_NAME_FIELD_NUMBER;
            hash = (53 * hash) + getCustomerName().hashCode();
            hash = (37 * hash) + IS_VALID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getIsValid());
            hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
            hash = (53 * hash) + getMessageId().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<TrackingEvent> getParserForType() {
            return PARSER;
        }

        public com.amazon.proto.TrackingEventProtos.TrackingEvent getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code TrackingEvent}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:TrackingEvent)
                com.amazon.proto.TrackingEventProtos.TrackingEventOrBuilder {
            private java.lang.Object programid_ = "";
            private java.lang.Object checksum_ = "";
            private int customerId_;
            private java.lang.Object userAgent_ = "";
            private java.lang.Object programName_ = "";
            private java.lang.Object customerName_ = "";
            private boolean isValid_;
            private java.lang.Object messageId_ = "";

            // Construct using com.amazon.proto.TrackingEventProtos.TrackingEvent.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return com.amazon.proto.TrackingEventProtos.internal_static_TrackingEvent_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return com.amazon.proto.TrackingEventProtos.internal_static_TrackingEvent_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                com.amazon.proto.TrackingEventProtos.TrackingEvent.class, com.amazon.proto.TrackingEventProtos.TrackingEvent.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                programid_ = "";

                checksum_ = "";

                customerId_ = 0;

                userAgent_ = "";

                programName_ = "";

                customerName_ = "";

                isValid_ = false;

                messageId_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return com.amazon.proto.TrackingEventProtos.internal_static_TrackingEvent_descriptor;
            }

            public com.amazon.proto.TrackingEventProtos.TrackingEvent getDefaultInstanceForType() {
                return com.amazon.proto.TrackingEventProtos.TrackingEvent.getDefaultInstance();
            }

            public com.amazon.proto.TrackingEventProtos.TrackingEvent build() {
                com.amazon.proto.TrackingEventProtos.TrackingEvent result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.amazon.proto.TrackingEventProtos.TrackingEvent buildPartial() {
                com.amazon.proto.TrackingEventProtos.TrackingEvent result = new com.amazon.proto.TrackingEventProtos.TrackingEvent(this);
                result.programid_ = programid_;
                result.checksum_ = checksum_;
                result.customerId_ = customerId_;
                result.userAgent_ = userAgent_;
                result.programName_ = programName_;
                result.customerName_ = customerName_;
                result.isValid_ = isValid_;
                result.messageId_ = messageId_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof com.amazon.proto.TrackingEventProtos.TrackingEvent) {
                    return mergeFrom((com.amazon.proto.TrackingEventProtos.TrackingEvent) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(com.amazon.proto.TrackingEventProtos.TrackingEvent other) {
                if (other == com.amazon.proto.TrackingEventProtos.TrackingEvent.getDefaultInstance()) return this;
                if (!other.getProgramid().isEmpty()) {
                    programid_ = other.programid_;
                    onChanged();
                }
                if (!other.getChecksum().isEmpty()) {
                    checksum_ = other.checksum_;
                    onChanged();
                }
                if (other.getCustomerId() != 0) {
                    setCustomerId(other.getCustomerId());
                }
                if (!other.getUserAgent().isEmpty()) {
                    userAgent_ = other.userAgent_;
                    onChanged();
                }
                if (!other.getProgramName().isEmpty()) {
                    programName_ = other.programName_;
                    onChanged();
                }
                if (!other.getCustomerName().isEmpty()) {
                    customerName_ = other.customerName_;
                    onChanged();
                }
                if (other.getIsValid() != false) {
                    setIsValid(other.getIsValid());
                }
                if (!other.getMessageId().isEmpty()) {
                    messageId_ = other.messageId_;
                    onChanged();
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.amazon.proto.TrackingEventProtos.TrackingEvent parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.amazon.proto.TrackingEventProtos.TrackingEvent) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>string programid = 1;</code>
             */
            public java.lang.String getProgramid() {
                java.lang.Object ref = programid_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    programid_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string programid = 1;</code>
             */
            public Builder setProgramid(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                programid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string programid = 1;</code>
             */
            public com.google.protobuf.ByteString
            getProgramidBytes() {
                java.lang.Object ref = programid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    programid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string programid = 1;</code>
             */
            public Builder setProgramidBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                programid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string programid = 1;</code>
             */
            public Builder clearProgramid() {

                programid_ = getDefaultInstance().getProgramid();
                onChanged();
                return this;
            }

            /**
             * <code>string checksum = 2;</code>
             */
            public java.lang.String getChecksum() {
                java.lang.Object ref = checksum_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    checksum_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string checksum = 2;</code>
             */
            public Builder setChecksum(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                checksum_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string checksum = 2;</code>
             */
            public com.google.protobuf.ByteString
            getChecksumBytes() {
                java.lang.Object ref = checksum_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    checksum_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string checksum = 2;</code>
             */
            public Builder setChecksumBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                checksum_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string checksum = 2;</code>
             */
            public Builder clearChecksum() {

                checksum_ = getDefaultInstance().getChecksum();
                onChanged();
                return this;
            }

            /**
             * <code>int32 customer_id = 3;</code>
             */
            public int getCustomerId() {
                return customerId_;
            }

            /**
             * <code>int32 customer_id = 3;</code>
             */
            public Builder setCustomerId(int value) {

                customerId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 customer_id = 3;</code>
             */
            public Builder clearCustomerId() {

                customerId_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>string user_agent = 4;</code>
             */
            public java.lang.String getUserAgent() {
                java.lang.Object ref = userAgent_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    userAgent_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string user_agent = 4;</code>
             */
            public Builder setUserAgent(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                userAgent_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string user_agent = 4;</code>
             */
            public com.google.protobuf.ByteString
            getUserAgentBytes() {
                java.lang.Object ref = userAgent_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    userAgent_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string user_agent = 4;</code>
             */
            public Builder setUserAgentBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                userAgent_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string user_agent = 4;</code>
             */
            public Builder clearUserAgent() {

                userAgent_ = getDefaultInstance().getUserAgent();
                onChanged();
                return this;
            }

            /**
             * <code>string program_name = 5;</code>
             */
            public java.lang.String getProgramName() {
                java.lang.Object ref = programName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    programName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string program_name = 5;</code>
             */
            public Builder setProgramName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                programName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string program_name = 5;</code>
             */
            public com.google.protobuf.ByteString
            getProgramNameBytes() {
                java.lang.Object ref = programName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    programName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string program_name = 5;</code>
             */
            public Builder setProgramNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                programName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string program_name = 5;</code>
             */
            public Builder clearProgramName() {

                programName_ = getDefaultInstance().getProgramName();
                onChanged();
                return this;
            }

            /**
             * <code>string customer_name = 6;</code>
             */
            public java.lang.String getCustomerName() {
                java.lang.Object ref = customerName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    customerName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string customer_name = 6;</code>
             */
            public Builder setCustomerName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                customerName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string customer_name = 6;</code>
             */
            public com.google.protobuf.ByteString
            getCustomerNameBytes() {
                java.lang.Object ref = customerName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    customerName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string customer_name = 6;</code>
             */
            public Builder setCustomerNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                customerName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string customer_name = 6;</code>
             */
            public Builder clearCustomerName() {

                customerName_ = getDefaultInstance().getCustomerName();
                onChanged();
                return this;
            }

            /**
             * <code>bool is_valid = 7;</code>
             */
            public boolean getIsValid() {
                return isValid_;
            }

            /**
             * <code>bool is_valid = 7;</code>
             */
            public Builder setIsValid(boolean value) {

                isValid_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bool is_valid = 7;</code>
             */
            public Builder clearIsValid() {

                isValid_ = false;
                onChanged();
                return this;
            }

            /**
             * <code>string message_id = 8;</code>
             */
            public java.lang.String getMessageId() {
                java.lang.Object ref = messageId_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    messageId_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string message_id = 8;</code>
             */
            public Builder setMessageId(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                messageId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string message_id = 8;</code>
             */
            public com.google.protobuf.ByteString
            getMessageIdBytes() {
                java.lang.Object ref = messageId_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    messageId_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string message_id = 8;</code>
             */
            public Builder setMessageIdBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                messageId_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string message_id = 8;</code>
             */
            public Builder clearMessageId() {

                messageId_ = getDefaultInstance().getMessageId();
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:TrackingEvent)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
