// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tracking.proto

package consumer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TrackingEvent struct {
	Programid            string   `protobuf:"bytes,1,opt,name=programid" json:"programid,omitempty"`
	Checksum             string   `protobuf:"bytes,2,opt,name=checksum" json:"checksum,omitempty"`
	CustomerId           int32    `protobuf:"varint,3,opt,name=customer_id,json=customerId" json:"customer_id,omitempty"`
	UserAgent            string   `protobuf:"bytes,4,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
	ProgramName          string   `protobuf:"bytes,5,opt,name=program_name,json=programName" json:"program_name,omitempty"`
	CustomerName         string   `protobuf:"bytes,6,opt,name=customer_name,json=customerName" json:"customer_name,omitempty"`
	IsValid              bool     `protobuf:"varint,7,opt,name=is_valid,json=isValid" json:"is_valid,omitempty"`
	MessageId            string   `protobuf:"bytes,8,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TrackingEvent) Reset()         { *m = TrackingEvent{} }
func (m *TrackingEvent) String() string { return proto.CompactTextString(m) }
func (*TrackingEvent) ProtoMessage()    {}
func (*TrackingEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_tracking_e51492b0a54f9ea5, []int{0}
}
func (m *TrackingEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TrackingEvent.Unmarshal(m, b)
}
func (m *TrackingEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TrackingEvent.Marshal(b, m, deterministic)
}
func (dst *TrackingEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TrackingEvent.Merge(dst, src)
}
func (m *TrackingEvent) XXX_Size() int {
	return xxx_messageInfo_TrackingEvent.Size(m)
}
func (m *TrackingEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TrackingEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TrackingEvent proto.InternalMessageInfo

func (m *TrackingEvent) GetProgramid() string {
	if m != nil {
		return m.Programid
	}
	return ""
}

func (m *TrackingEvent) GetChecksum() string {
	if m != nil {
		return m.Checksum
	}
	return ""
}

func (m *TrackingEvent) GetCustomerId() int32 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func (m *TrackingEvent) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

func (m *TrackingEvent) GetProgramName() string {
	if m != nil {
		return m.ProgramName
	}
	return ""
}

func (m *TrackingEvent) GetCustomerName() string {
	if m != nil {
		return m.CustomerName
	}
	return ""
}

func (m *TrackingEvent) GetIsValid() bool {
	if m != nil {
		return m.IsValid
	}
	return false
}

func (m *TrackingEvent) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func init() {
	proto.RegisterType((*TrackingEvent)(nil), "TrackingEvent")
}

func init() { proto.RegisterFile("tracking.proto", fileDescriptor_tracking_e51492b0a54f9ea5) }

var fileDescriptor_tracking_e51492b0a54f9ea5 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xd0, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x06, 0x60, 0xa5, 0xd0, 0x36, 0xbd, 0xb6, 0x08, 0x99, 0xc5, 0x20, 0x10, 0x01, 0x06, 0x32,
	0x75, 0xe1, 0x09, 0xa8, 0xc4, 0xd0, 0x05, 0xa1, 0x08, 0xb1, 0x46, 0x87, 0x7d, 0x0a, 0x56, 0xb1,
	0x5d, 0xd9, 0x4e, 0x07, 0x5e, 0x81, 0x97, 0x46, 0x76, 0xd2, 0xa0, 0x8e, 0xfe, 0xee, 0x97, 0xef,
	0xd7, 0xc1, 0x59, 0x70, 0x28, 0xb6, 0xca, 0x34, 0xab, 0x9d, 0xb3, 0xc1, 0xde, 0xff, 0x8e, 0x60,
	0xf9, 0xde, 0xd3, 0xcb, 0x9e, 0x4c, 0x60, 0xd7, 0x30, 0xdb, 0x39, 0xdb, 0x38, 0xd4, 0x4a, 0xf2,
	0xac, 0xc8, 0xca, 0x59, 0xf5, 0x0f, 0xec, 0x0a, 0x72, 0xf1, 0x45, 0x62, 0xeb, 0x5b, 0xcd, 0x47,
	0x69, 0x38, 0xbc, 0xd9, 0x2d, 0xcc, 0x45, 0xeb, 0x83, 0xd5, 0xe4, 0x6a, 0x25, 0xf9, 0x49, 0x91,
	0x95, 0xe3, 0x0a, 0x0e, 0xb4, 0x91, 0xec, 0x06, 0xa0, 0xf5, 0xe4, 0x6a, 0x6c, 0xc8, 0x04, 0x7e,
	0xda, 0xfd, 0x1d, 0xe5, 0x39, 0x02, 0xbb, 0x83, 0x45, 0xbf, 0xa8, 0x36, 0xa8, 0x89, 0x8f, 0x53,
	0x60, 0xde, 0xdb, 0x2b, 0x6a, 0x62, 0x0f, 0xb0, 0x1c, 0x56, 0xa4, 0xcc, 0x24, 0x65, 0x16, 0x07,
	0x4c, 0xa1, 0x4b, 0xc8, 0x95, 0xaf, 0xf7, 0xf8, 0xad, 0x24, 0x9f, 0x16, 0x59, 0x99, 0x57, 0x53,
	0xe5, 0x3f, 0xe2, 0x33, 0x36, 0xd0, 0xe4, 0x3d, 0x36, 0x14, 0x1b, 0xe6, 0x5d, 0x83, 0x5e, 0x36,
	0x72, 0xfd, 0x08, 0xe7, 0xc2, 0xea, 0x15, 0x6a, 0xfc, 0xb1, 0xa6, 0xbb, 0xd0, 0xfa, 0xe2, 0xe8,
	0x3c, 0x6f, 0xd1, 0xfc, 0xe7, 0x24, 0xcd, 0x9e, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xb5,
	0x9c, 0xfa, 0x4f, 0x01, 0x00, 0x00,
}
