Description: >
    This template deploys an Elasticache cluster to the provided VPC and subnets 

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    InstanceType: 
        Description: Which instance type should we use to build the ECS cluster?
        Type: String
        Default: cache.m4.large

    VPC:
        Description: Choose which VPC this ECS cluster should be deployed to
        Type: AWS::EC2::VPC::Id

    Subnets:
        Description: Choose which subnets this ECS cluster should be deployed to
        Type: List<AWS::EC2::Subnet::Id>

    SecurityGroup:
        Description: Select the Security Group to use for the ECS cluster hosts
        Type: AWS::EC2::SecurityGroup::Id

Resources:

  CacheSubnetGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties:
      CacheSubnetGroupName: !Sub ${EnvironmentName}-Subnet-${AWS::Region}
      Description: The subnet group for the reactive application architecture 
      SubnetIds: !Ref Subnets 

  ReplicationGroup:
    Type: "AWS::ElastiCache::ReplicationGroup"
    Properties: 
      AutomaticFailoverEnabled: True
      AutoMinorVersionUpgrade: True
      CacheNodeType: !Ref InstanceType
      CacheSubnetGroupName: !Ref CacheSubnetGroup
      Engine: redis
      EngineVersion: 5.0
      NumCacheClusters: 2
      Port: 6379
      ReplicationGroupDescription: !Sub ${EnvironmentName}-ReplicationGroup-${AWS::Region}
      SecurityGroupIds:
        - !Ref SecurityGroup

Outputs:

    RedisHost:
        Description: A reference to the ElastiCache cluster
        Value: !GetAtt ReplicationGroup.PrimaryEndPoint.Address

    RedisPort:
        Description: A reference to the ElastiCache cluster
        Value: !GetAtt ReplicationGroup.PrimaryEndPoint.Port
