FROM debian:9-slim
LABEL maintainer="Sascha Möllering <smoell@amazon.de>"

WORKDIR /usr/bin
COPY target/reactive-vertx /usr/bin/reactive-vertx

HEALTHCHECK --interval=5s --timeout=3s --retries=3 \
  CMD curl -f http://localhost:8080/health/check || exit 1

CMD [ "/usr/bin/reactive-vertx" ]